/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tweetsender;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollBar;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author henriquevalcanaia
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
        taTweet.setLineWrap(true);
        taTweet.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbToken = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTweet = new javax.swing.JTextArea();
        pwToken = new javax.swing.JPasswordField();
        cbShowToken = new javax.swing.JCheckBox();
        lbTweet = new javax.swing.JLabel();
        lbCountChar = new javax.swing.JLabel();
        btSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbToken.setText("Token:");

        taTweet.setColumns(20);
        taTweet.setRows(5);
        taTweet.setTabSize(3);
        taTweet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taTweetKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taTweetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taTweetKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(taTweet);

        pwToken.setToolTipText("Insira seu token aqui");
        pwToken.setEchoChar('*');
        pwToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwTokenActionPerformed(evt);
            }
        });

        cbShowToken.setText("Show token");
        cbShowToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowTokenActionPerformed(evt);
            }
        });

        lbTweet.setText("Tweet:");

        lbCountChar.setForeground(new java.awt.Color(51, 153, 0));
        lbCountChar.setText("0/160");

        btSend.setText("Send");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbTweet)
                    .add(lbToken)
                    .add(layout.createSequentialGroup()
                        .add(pwToken)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cbShowToken))
                    .add(layout.createSequentialGroup()
                        .add(lbCountChar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btSend))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lbToken)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pwToken, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cbShowToken))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lbTweet)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbCountChar)
                    .add(btSend)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbShowTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowTokenActionPerformed
        char CHAR_PONTO = (char) 9679;
        char CHAR_ASTERISCO = (char) 42;
        char CHAR_NENHUM = (char) 0;
        if(cbShowToken.isSelected()){
            pwToken.setEchoChar(CHAR_NENHUM);
        }else{
            pwToken.setEchoChar(CHAR_ASTERISCO);
        }
    }//GEN-LAST:event_cbShowTokenActionPerformed

    private void pwTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwTokenActionPerformed

    private void taTweetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTweetKeyPressed
    }//GEN-LAST:event_taTweetKeyPressed

    private void taTweetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTweetKeyReleased
    }//GEN-LAST:event_taTweetKeyReleased

    private void taTweetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTweetKeyTyped
        String lsLength;
        Integer liLength;
        liLength = taTweet.getText().length();
        lsLength = liLength.toString();
        lbCountChar.setText(lsLength + "/160");
        if(liLength <= 160){
            lbCountChar.setForeground(new Color(51, 153, 0));
        }else{
            if(liLength > 160){
                lbCountChar.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_taTweetKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSend;
    private javax.swing.JCheckBox cbShowToken;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCountChar;
    private javax.swing.JLabel lbToken;
    private javax.swing.JLabel lbTweet;
    private javax.swing.JPasswordField pwToken;
    private javax.swing.JTextArea taTweet;
    // End of variables declaration//GEN-END:variables
}
