/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.controller.Controller;
import gnu.io.CommPortIdentifier;
import java.util.Enumeration;
import javax.swing.JMenuItem;
import javax.swing.JRadioButtonMenuItem;

/**
 *
 * @author henriquevalcanaia
 */
public class MainWindow extends javax.swing.JFrame {
    
    Controller c;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
        initController();

    }
    
    private void initController(){
        this.c = new Controller();
        this.c.setLbCountChar(lbCountChar);
        this.c.setTaTweet(taTweet);
        this.c.setCbShowToken(cbShowToken);
        this.c.setPfToken(pfToken);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lbToken = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTweet = new javax.swing.JTextArea();
        pfToken = new javax.swing.JPasswordField();
        cbShowToken = new javax.swing.JCheckBox();
        lbTweet = new javax.swing.JLabel();
        lbCountChar = new javax.swing.JLabel();
        btSend = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        mOptions = new javax.swing.JMenu();
        miScanPorts = new javax.swing.JMenuItem();
        mSerialPort = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        miToken = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miAbout = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbToken.setText("Token:");

        taTweet.setColumns(20);
        taTweet.setRows(5);
        taTweet.setTabSize(3);
        taTweet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taTweetKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taTweetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taTweetKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(taTweet);

        pfToken.setText("107308370-ZDZViafGcTrHVo2eRnVFBcWoRxiTdba5kJWcvcR5");
        pfToken.setToolTipText("Insira seu token aqui");
        pfToken.setEchoChar('*');
        pfToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfTokenActionPerformed(evt);
            }
        });

        cbShowToken.setText("Show token");
        cbShowToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowTokenActionPerformed(evt);
            }
        });

        lbTweet.setText("Tweet:");

        lbCountChar.setForeground(new java.awt.Color(51, 153, 0));
        lbCountChar.setText("0/160");

        btSend.setText("Send");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        mOptions.setText("Options");

        miScanPorts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        miScanPorts.setText("Scan serial ports");
        mOptions.add(miScanPorts);

        mSerialPort.setText("Serial port");
        mSerialPort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mSerialPortMouseEntered(evt);
            }
        });
        mSerialPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSerialPortActionPerformed(evt);
            }
        });

        jMenuItem1.setText("This menu is populated dynamically");
        mSerialPort.add(jMenuItem1);

        mOptions.add(mSerialPort);

        jMenuBar2.add(mOptions);

        mHelp.setText("Help");

        miToken.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        miToken.setText("How to get a token");
        miToken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miTokenMouseClicked(evt);
            }
        });
        miToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTokenActionPerformed(evt);
            }
        });
        mHelp.add(miToken);
        mHelp.add(jSeparator1);

        miAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        mHelp.add(miAbout);

        jMenuBar2.add(mHelp);

        setJMenuBar(jMenuBar2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(pfToken, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cbShowToken))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(lbCountChar)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(btSend))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lbTweet)
                                    .add(lbToken))
                                .add(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lbToken)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pfToken, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cbShowToken))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lbTweet)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbCountChar)
                    .add(btSend))
                .add(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbShowTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowTokenActionPerformed
        c.showToken(cbShowToken.isSelected());
    }//GEN-LAST:event_cbShowTokenActionPerformed

    private void pfTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfTokenActionPerformed

    private void taTweetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTweetKeyPressed
        
    }//GEN-LAST:event_taTweetKeyPressed

    private void taTweetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTweetKeyReleased
        c.calcTweetLength(taTweet, lbCountChar);
    }//GEN-LAST:event_taTweetKeyReleased

    private void taTweetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTweetKeyTyped
        c.calcTweetLength(taTweet, lbCountChar);
    }//GEN-LAST:event_taTweetKeyTyped

    private void miTokenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miTokenMouseClicked
        
    }//GEN-LAST:event_miTokenMouseClicked

    private void miTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTokenActionPerformed
        c.getToken();
    }//GEN-LAST:event_miTokenActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        c.showHelp();
    }//GEN-LAST:event_miAboutActionPerformed

    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
        c.createPortsMenu(mSerialPort);
    }//GEN-LAST:event_btSendActionPerformed

    private void mSerialPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSerialPortActionPerformed
        
    }//GEN-LAST:event_mSerialPortActionPerformed

    private void mSerialPortMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSerialPortMouseEntered
    }//GEN-LAST:event_mSerialPortMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSend;
    private javax.swing.JCheckBox cbShowToken;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbCountChar;
    private javax.swing.JLabel lbToken;
    private javax.swing.JLabel lbTweet;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenu mOptions;
    private javax.swing.JMenu mSerialPort;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miScanPorts;
    private javax.swing.JMenuItem miToken;
    private javax.swing.JPasswordField pfToken;
    private javax.swing.JTextArea taTweet;
    // End of variables declaration//GEN-END:variables
}
